name:                hoice-haskell
version:             0.1.0.0
license:             BSD3
author:              "ubikium"
maintainer:          "ubikium@gmail.com"
copyright:           "2020 ubikium"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/crvdgc/hoice-haskell#readme>

dependencies:
- base >= 4.8 && < 5.0
- z3 >= 408 && < 500
- smt2-parser == 0.1.*
- text
- array
- containers
- mios >= 1.6.2 && < 1.7.0
- mtl
- process
- pretty-simple == 4.0.0.0

extra-libraries: z3

library:
  source-dirs: src

executables:
  hoice-ex:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hoice-haskell
    - optparse-applicative

tests:
  hoice-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hoice-haskell
    - tasty
    - tasty-hunit
