name:                hoice-haskell
version:             0.1.0.0
license:             BSD3
author:              "ubikium"
maintainer:          "ubikium@gmail.com"
copyright:           "2020 ubikium"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/crvdgc/hoice-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- z3 >= 408 && < 500
- smt2-parser == 0.1.*
- text
- array
- containers
- mtl

library:
  source-dirs: src

executables:
  hoice-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hoice-haskell

tests:
  hoice-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hoice-haskell
    - HUnit >= 1.0 && < 2.0
